apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 2
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: my-flask-app
        image: sanakhanlibre/my_flask_app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  labels:
    app: flask
spec:
  selector:
    app: flask
  type: NodePort
  ports:
  - nodePort: 31113
    port: 5000
    targetPort: 5000